import {
  CasingProps,
  ColorProps,
  CursorProps,
  DisplayProps,
  ElevationProps,
  FlexProps,
  FontProps,
  FontSizeProps,
  LetterSpacingProps,
  LineHeightProps,
  RadiusProps,
  SizingProps,
  TextAlignProps,
  TransitionProps,
  UnderlineProps,
  UnitsAroundProps,
} from '@shallot-ui/theme'

export interface TextProps
  extends ColorProps,
    CursorProps,
    DisplayProps,
    ElevationProps,
    FlexProps,
    FontProps,
    FontSizeProps,
    LetterSpacingProps,
    LineHeightProps,
    RadiusProps,
    SizingProps,
    TextAlignProps,
    TransitionProps,
    UnderlineProps,
    UnitsAroundProps,
    CasingProps {}
