import { CSSProperties, ReactNode } from 'react'
import {
  AnimationProps,
  CasingProps,
  ColorProps,
  CursorProps,
  DisplayProps,
  ElevationProps,
  FlexProps,
  FontProps,
  FontSizeProps,
  LetterSpacingProps,
  LineHeightProps,
  RadiusProps,
  SizingProps,
  TextAlignProps,
  TransitionProps,
  UnderlineProps,
  UnitsAroundProps,
} from '@shallot-ui/theme'

export interface TextProps
  extends AnimationProps,
    CasingProps,
    ColorProps,
    CursorProps,
    DisplayProps,
    ElevationProps,
    FlexProps,
    FontProps,
    FontSizeProps,
    LetterSpacingProps,
    LineHeightProps,
    RadiusProps,
    SizingProps,
    TextAlignProps,
    TransitionProps,
    UnderlineProps,
    UnitsAroundProps {}
