import { NextPage } from 'next'
import Head from 'next/head'

import { HomeLayout } from '@/layouts/Home'

const Home: NextPage = () => (
  <>
    <Head>
      <title>Human. Starter</title>
      <meta
        name="description"
        content="Generated by the Human Web Starter Kit"
      />
    </Head>
    <HomeLayout />
  </>
)

export default Home
