name: Check Types
on:
  pull_request:
jobs:
  check-types:
    name: Run action
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'functions'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Check Types
        run: yarn check-types
