name: ublish-packages

on:
  push:
    branches:
      - main
      - develop

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-packages:
    name: publish-packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn

      - name: Create publish-packages Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: |
            if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
              yarn publish-packages --pre-release
            else
              yarn publish-packages
            fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Send a Slack notification if a publish happens
        if: steps.changesets.outputs.published == 'true'
        # You can do something when a publish happens.
        run: my-slack-bot send-notification --message "A new version of Shallot was published!"
